# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Velocity Controllers ---------------------------------------
rear_left_wheel_vel_controller:
  type: velocity_controllers/JointVelocityController
  #type: effort_controllers/JointVelocityController
  joint: rear_left_wheel
  pid: {p: 0.2, i: 1.0, d: 0.0, i_clamp: 0.0}
rear_right_wheel_vel_controller:
  type: velocity_controllers/JointVelocityController
  #type: effort_controllers/JointVelocityController
  joint: rear_right_wheel
  pid: {p: 0.2, i: 1.0, d: 0.0, i_clamp: 0.0}
#front_left_wheel_vel_controller:
  #type: velocity_controllers/JointVelocityController
  #type: effort_controllers/JointVelocityController
  #joint: front_left_wheel
  #pid: {p: 0.2, i: 1.0, d: 0.0, i_clamp: 0.0}
#front_right_wheel_vel_controller:
  #type: velocity_controllers/JointVelocityController
  #type: effort_controllers/JointVelocityController
  #joint: front_right_wheel
  #pid: {p: 0.2, i: 1.0, d: 0.0, i_clamp: 0.0}


# Position Controllers ---------------------------------------
left_hinge_position_controller:
  joint: left_hinge
  type: effort_controllers/JointPositionController
  pid: {p: 10.0, i: 2.0, d: 0.4}
right_hinge_position_controller:
  joint: right_hinge
  type: effort_controllers/JointPositionController
  pid: {p: 10.0, i: 2.0, d: 0.4}

